### ISSUE TITLE
VersionConflict Cython

### ISSUE THREAD

**Issue by andresriancho** [tpetmanson/ac#1]
Getting this when running `pip install aca`:

```
pkg_resources.VersionConflict: (Cython 0.26 (/home/john/pch/virtualenvs/w3af/lib/python2.7/site-packages), Requirement.parse('Cython<0.26,>=0.25.0'))
```
The installation then fails

**Comment by tpetmanson** [comment]
Thanks for reporting the problem. It seems you have already Cython installed (probably newest version). If it possible for you to use older version of Cython >=0.25.0, <0.26, you should be able to install aca without waiting for the fix. 

As for the fix, I believe upgrading the dependency version in the library would resolve this error. I'll try to work this out and upload new version of the library to pypi as soon as possible.

**Comment by tpetmanson** [comment]
The Cython dependency version constraints are now relaxed in version 1.0
